;;;; GTK 4 Demo
;;;;
;;;; 2024-4-1

(in-package :gtk4-demo)

(defparameter *gtk-demos*
   '(("GTK 4 Lisp Demo"
      nil
      nil
      "gtk4-demo"
      "gtk4-demo.lisp"
      "gtk4-demo-catalog.lisp"
      "gtk4-demo-package.lisp"
      "gtk4-demo.asd"
      "main.ui"
      "main-listitem.ui"
      "gtk4-demo.xml")

     "Application"
     (("Simple Application"
       ":application"
       "APPLICATION-SIMPLE"
       "gtk4-application"
       "application-simple.lisp"
       :keywords
       "GtkApplication"
       "gtk:application"
       ":flags" "g:application-flags" ":application-id"
       ":default-flags"
       "g:application-hold"
       "g:application-release"
       "g:application-run"
       "GtkApplicationWindow"
       "gtk:application-window"
       ":application"
       ":title"
       ":default-width"
       ":default-height"
       "g:signal-connect"
       "::activate")
      ("Application Resources"
       ":application"
       "APPLICATION-RESOURCES"
       "gtk4-application"
       "application-resources.lisp"
       "resource/menus.ui"
       "resource/help-overlay.ui"
       "gtk4-application.xml"
       :keywords
       "GtkApplication"
       "gtk:application"
       ":flags"
       ":application-id"
       "g:application-flags"
       ":default-flags"
       "gtk:application-menubar"
       "gtk:application-menu-by-id"
       "gtk:application-accels-for-action"
       "g:application-resource-base-path"
       "g:application-hold"
       "g:application-release"
       "g:application-run"
       "g:action-map-add-action-entries"
       "GtkApplicationWindow"
       "gtk:application-window"
       ":application"
       ":title"
       ":show-menubar"
       ":icon-name"
       ":default-width"
       ":default-height"
       "gtk:application-window-help-overlay"
       "g:with-resource"
       "gtk:icon-theme-for-display"
       "gtk:icon-theme-icon-names"
       "gtk:icon-theme-resource-path"
       "gdk:display-default"
       "gtk:show-about-dialog"
       ":program-name"
       ":logo-icon-name"
       ":authors"
       ":comments"
       "g:signal-connect"
       "::startup"
       "::activate")
      ("Application Menubar"
       ":application"
       "APPLICATION-MENUBAR"
       "gtk4-application"
       "application-menubar.lisp"
       "resource/menubar.ui"
       :keywords
       "GtkApplication"
       "gtk:application"
       ":application-id"
       ":flags"
       "g:application-flags"
       ":default-flags"
       "gtk:application-menubar"
       "gtk:builder"
       "gtk:builder-add-from-file"
       "gtk:builder-object"
       "gtk:label"
       ":label"
       ":xalign"
       ":margin-start"
       ":margin-top"
       ":margin-bottom"
       "gtk:label-text"
       "gtk:box"
       ":orientation"
       "gtk:orientation"
       ":vertical"
       "gtk:box-append"
       "gtk:application-window"
       ":application"
       ":title"
       ":child"
       ":show-menubar"
       ":default-width"
       ":default-height"
       "gtk:text-view"
       ":top-margin"
       ":bottom-margin"
       ":left-margin"
       ":vexpand"
       "gtk:align"
       ":fill"
       "gtk:winow-present"
       "g:object-data"
       "g:source-remove"
       "g:timeout-add"
       "g:+source-remove+"
       "g:action-name"
       "g:action-state"
       "g:variant-boolean"
       "g:variant-string"
       "g:action-map-add-action-entries"
       "g:application-run"
       "g:signal-connect"
       "::startup"
       "::activate")
      ("Sunny"
       ":application"
       "SUNNY"
       "gtk4-application"
       "sunny.lisp"
       :keywords
       "GtkApplication"
       "gtk:application"
       ":application-id"
       ":flags"
       "g:application-flags"
       ":handles-open"
       "g:application-name"
       "g:application-activate"
       "g:application-run"
       "gtk:application-active-window"
       "gtk:application-windows"
       "gtk:application-menubar"
       "gtk:application-accels-for-action"
       "gtk:show-about-dialog"
       ":modal"
       ":program-name"
       ":logo-icon-name"
       ":comments"
       "gtk:text-view"
       ":monospace"
       "gtk:text-view-buffer"
       "gtk:text-buffer-load-file"
       "gtk:scrolled-window"
       ":child"
       ":hexpand"
       ":vexpand"
       "gtk:overlay"
       "gtk:builder"
       "gtk:builder-object"
       "gtk:builder-add-from-string"
       "gtk:application-window"
       ":application"
       ":title"
       ":show-menbar"
       ":icon-name"
       ":default-width"
       ":default-height"
       "gtk:window-destroy"
       "g:action-map-add-action-entries"
       "gtk:settings-default"
       "gtk:settings-gtk-shell-show-app-menu"
       "g:file"
       "g:file-get-parse-name"
       "gobject:define-gobject-subclass"
       "g:signal-connect"
       "::startup"
       "::open"
       "::activate"))

     "Theming in GTK"                                       ; Title
     (("CSS Accordion"                                      ; Title
       ":WINDOW"                                            ; Type
       "DO-CSS-ACCORDION"                                   ; Function name
       "gtk4-example"                                       ; Package
       "css-accordion.lisp"                                 ; Filename
       "resource/css-accordion.css"                         ; Resources
       :keywords                                            ; Keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-path"
       "gtk:box"
       "gtk:box-append"
       "gtk:button-new-with-label"
       "gtk:frame"
       "gtk:window"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       ":orientation"
       ":halign"
       ":valign"
       ":child"
       ":application"
       ":title"
       ":default-width"
       ":default-height")
      ("CSS Basics"
       ":WINDOW"
       "DO-CSS-BASICS"
       "gtk4-example"
       "css-basics.lisp"
       "resource/css-basics.css"
       :keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-string"
       "gtk:css-section-start-location"
       "gtk:css-section-end-location"
       "gtk:css-locatin-lines"
       "gtk:css-location-line-bytes"
       "gtk:text-buffer"
       "gtk:text-buffer-text"
       "gtk:text-buffer-start-iter"
       "gtk:text-buffer-end-iter"
       "gtk:text-buffer-get-text"
       "gtk:text-buffer-iter-at-line-index"
       "gtk:text-buffer-apply-tag"
       "gtk:text-buffer-tag-table"
       "gtk:text-tag"
       "gtk:text-tag-table-add"
       "gtk:text-view"
       "gtk:scrolled-window"
       "gtk:window"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       "gdk:+event-stop+"
       "g:signal-connect"
       "::changed"
       "::parsing-error"
       ":buffer"
       ":child"
       ":application"
       ":title"
       ":default-width"
       ":default-height"
       ":name"
       ":underline")
      ("CSS Blendmodes"
       ":WINDOW"
       "DO-CSS-BLENDMODES"
       "gtk4-example"
       "css-blendmodes.lisp"
       "resource/css-blendmodes.ui"
       "resource/css-blendmodes.css"
       :keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-string"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:list-box"
       "gtk:list-box-insert"
       "gtk:list-box-select-row"
       "gtk:list-box-row"
       "gtk:list-box-row-child"
       "gtk:list-box-row-index"
       "gtk:label"
       "gtk:window-application"
       "gtk:scrolled-window-child"
       "gtk:widget-add-provider"
       "g:resource-load"
       "g:resources-register"
       "g:signal-emit"
       "g:signal-connect"
       "::row-activated"
       "::activate"
       ":label"
       ":xalign")
      ("CSS Multiple Backgrounds"
       ":window"
       "DO-CSS-MULTIPLEBGS"
       "gtk4-example"
       "css-multiplebgs.lisp"
       "resource/css-multiplebgs.css"
       :keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-string"
       "gtk:css-provider-load-from-path"
       "gtk:css-section-start-location"
       "gtk:css-section-end-location"
       "gtk:css-location-lines"
       "gtk:css-location-line-bytes"
       "gtk:box"
       "gtk:box-append"
       "gtk:text-buffer"
       "gtk:text-buffer-text"
       "gtk:text-buffer-start-iter"
       "gtk:text-buffer-end-iter"
       "gtk:text-buffer-remove-all-tags"
       "gtk:text-buffer-get-text"
       "gtk:text-buffer-iter-at-line-index"
       "gtk:text-buffer-apply-tag"
       "gtk:text-buffer-tag-table"
       "gtk:text-tag"
       "gtk:text-tag-table-add"
       "gtk:text-view"
       "gtk:scrolled-window"
       "gtk:paned"
       "gtk:overlay"
       "gtk:drawing-area"
       "gtk:toggle-button"
       "gtk:toggle-button-active"
       "gtk:toggle-button-group"
       "gtk:toggle-button-new-with-label"
       "gtk:button"
       "gtk:overlay-add-overlay"
       "gtk:window"
       "gtk:widget-add-css-class"
       "gtk:widget-name"
       "gtk:widget-add-provider"
       "gdk:+event-stop+"
       "g:signal-connect"
       "::toggled"
       "::changed"
       "::parsing-error"
       ":orientation"
       ":label"
       ":buffer"
       ":top-margin"
       ":monospace"
       ":child"
       ":width-request"
       ":height-request"
       ":position"
       ":wide-handle"
       ":start-child"
       ":end-child"
       ":name"
       ":vexpand"
       ":application"
       ":title"
       ":default-width"
       ":default-height"
       ":halign"
       ":valign"
       ":underline"
       ":margin-top"
       ":margin-end")
      ("CSS Pixbufs"
       ":window"
       "DO-CSS-PIXBUFS"
       "gtk4-example"
       "css-pixbufs.lisp"
       "resource/css-pixbufs.css"
       :keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-path"
       "gtk:box"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       ":orientation"
       ":halign"
       ":valign"
       ":application"
       ":child"
       ":title"
       ":default-width"
       ":default-height")
      ("CSS Shadows"
       ":window"
       "DO-CSS-SHADOWS"
       "gtk4-example"
       "css-shadows.lisp"
       "resource/css-shadows.css"
       :keywords
       "GtkCssProvider"
       "gtk:css-provider"
       "gtk:css-provider-load-from-string"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       "gtk:text-view"
       "gtk:text-buffer"
       "gtk:text-buffer-start-iter"
       "gtk:text-buffer-end-iter"
       "gtk:text-buffer-remove-all-tags"
       "gtk:text-buffer-text"
       "gtk:text-buffer-get-text"
       "gtk:text-buffer-iter-at-line-index"
       "gtk:text-buffer-apply-tag"
       "gtk:text-buffer-tag-table"
       "gtk:text-tag"
       "gtk:text-tag-table-add"
       "gtk:css-section-start-location"
       "gtk:css-section-end-location"
       "gtk:css-location-lines"
       "gtk:css-location-line-bytes"
       "gtk:box"
       "gtk:scrolled-window"
       "gtk:paned-window"
       "gtk:window"
       "gdk:+event-stop+"
       "g:signal-connect"
       "::changed"
       "::parsing-error"
       ":orientation"
       ":css-name"
       ":icon-name"
       ":label"
       ":monospace"
       ":top-margin"
       ":buffer"
       ":child"
       ":start-child"
       ":end-child"
       ":position"
       ":shrink-start-child"
       ":wide-handle"
       ":application"
       ":title"
       ":default-height"
       ":default-width"
       ":name"
       ":underline"))

     "Interface Builder"
     (("Builder"
       ":window"
       "DO-BUILDER"
       "gtk4-example"
       "builder.lisp"
       "resource/builder.ui"
       :keywords
       "GtkBuilder"
       "gtk:builder"))

     "Windows"
     (("Simple Window"
       ":window"
       "DO-WINDOW-SIMPLE"
       "gtk4-example"
       "window-simple.lisp"
       :keywords
       "GtkWindow"
       "gtk:window"
       "gtk:window-application"
       "gtk:window-present"
       ":title")
      ("Simple Message Dialog"
       ":dialog"
       "CREATE-MESSAGE-DIALOG-SIMPLE"
       "gtk4-example"
       "message-dialog-simple.lisp"
       :keywords
       "GtkMessageDialog"
       "gtk:message-dialog"
       "gtk:message-dialog-new"
       "gtk:message-dialog-secondary-text"
       "gtk:window-destroy"
       "gtk:window-present"
       ;; Properties
       ":transient-for"
       ":modal"
       ":message-type" "gtk:message-type" ":info"
       ":buttons"
       ":text"
       ":secondary-text"
       ;; Signals
       "::response")
       (("Variant 1"
       ":dialog"
       "CREATE-MESSAGE-DIALOG-SIMPLE"
       "gtk4-example"
       "message-dialog-simple.lisp")
       ("Variant 2"
       ":dialog"
       "CREATE-MESSAGE-DIALOG-SIMPLE2"
       "gtk4-example"
       "message-dialog-simple.lisp"))

      ("Various Dialogs"
       ":window"
       "DO-DIALOG-VARIOUS"
       "gtk4-example"
       "dialog-various.lisp"
       "resource/dialog.ui"
       :keywords
       "GtkDialog"
       "GtkMessageDialog"
       "GtkAboutDialog"
       "gtk:dialog"
       "gtk:dialog-content-area"
       "gtk:dialog-add-button"
       "gtk:dialog-set-default-response"
       "gtk:message-dialog"
       "gtk:about-dialog"
       "gtk:show-about-dialog"
       "gtk:window"
       "gtk:window-destroy"
       "gtk:window-present"
       "gtk:window-transient-for"
       "gtk:box"
       "gtk:box-append"
       "gtk:label"
       "gtk:builder"
       "gtk:builder-add-from-file"
       "gtk:builder-object"
       "gtk:check-button"
       "gtk:check-button-active"
       "gtk:check-button-label"
       "gtk:check-button-new-with-label"
       "gtk:check-button-group"
       "gtk:button"
       "g:signal-connect"
       ;; Signals
       "::response"
       "::clicked"
       "::toggled"
       ;; Properties
       ":transient-for"
       ":modal"
       ":message-type"
       ":buttons"
       ":text"
       ":secondary-text"
       ":use-header-bar"
       ":title"
       ":program-name"
       ":version"
       ":copyright"
       ":website"
       ":website-label"
       ":license"
       ":authors"
       ":documenters"
       ":artists"
       ":logo-icon-name"
       ":wrap-license"
       ":orientation"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       ":spacing"
       ":application"
       ":type"
       ":child"
       ":default-width"
       ":default-height"
       ":wrap"
       ":label")
      ("Alert Dialog"
       ":dialog"
       "CREATE-ALERT-DIALOG"
       "gtk4-example"
       "alert-dialog.lisp"
       :keywords
       "GtkAlertDialog"
       "gtk:alert-dialog"
       "gtk:alert-dialog-choose"
       "gtk:alert-dialog-choose-finish"
       "g:cancellable-new"
       "g:canellable-cancel"
       "g:timeout-add-seconds")
      ("Assistant"
       ":window"
       "DO-ASSISTANT"
       "gtk4-example"
       "assistant.lisp"
       :keywords
       "GtkAssistant"
       "gtk:assistant"
       "gtk:assistant-current-page"
       "gtk:assistant-nth-page"
       "gtk:assistant-append-page"
       "gtk:assistant-commit"
       "gtk:assistant-page-title"
       "gtk:assistant-page-type"
       "gtk:assistant-page-complete")
       ("Application Window"
        ":window"
        "DO-APPLICATION-WINDOW"
        "gtk4-example"
        "application-window.lisp"
        :keywords
        "GtkApplicationWindow"
        "gtk:application-window"
        "gtk:application-menubar"
        "gtk:builder-object"
        "gtk:builder-add-from-string"))

     "Layout Containers"
     (("Box Append"
       ":window"
       "DO-BOX-APPEND"
       "gtk4-example"
       "box-append.lisp"
       :keywords
       "GtkBox"
       "gtk:box"
       "gtk:box-append"
       "gtk:button-new-with-label")
      ("Center Box"
       ":window"
       "DO-BOX-CENTER"
       "gtk4-example"
       "box-center.lisp"
       :keywords
       "GtkCenterBox"
       "gtk:center-box"
       "gtk:center-box-start-widget"
       "gtk:center-box-center-widget"
       "gtk:center-box-end-widget")
      ("Grid with spacing"
       ":window"
       "DO-GRID-SPACING"
       "gtk4-example"
       "grid-spacing.lisp"
       :keywords
       "GtkGrid"
       "gtk:grid"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       ":column-homogeneous"
       ":column-spacing"
       ":row-homogeneous"
       ":row-spacing"
       "gtk:grid-attach"
       "gtk:grid-row-spacing"
       "gtk:grid-column-spacing"
       "gtk:window"
       ":title"
       ":application"
       ":child"
       ":default-width"
       "gtk:button"
       "gtk:toggle-button"
       ":label"
       "gtk:toggle-button-active"
       "gtk:button-label"
       "g:signal-connect"
       "::toggled")
      ("Grid buildable"
       ":window"
       "DO-GRID-BUILDABLE"
       "gtk4-example"
       "grid-buildable.lisp"
       "resource/grid-buildable.ui"
       :keywords
       "GtkGrid"
       "gtk:grid"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:window"
       ":title"
       ":application"
       ":child")
      ("Revealer"
       ":window"
       "DO-REVEALER"
       "gtk4-example"
       "revealer.lisp"
       :keywords
       "GtkRevealer"
       "gtk:revealer"
       "gtk:align" ":halign" ":valign"
       "gtk:revealer-transition-type" ":transition-type"
       ":transition-duration"
       "gtk:grid"
       ":column-homogeneous"
       ":row-homogeneous"
       ":column-spacing"
       ":row-spacing"
       ":margin-bottom"
       ":margin-end"
       ":margin-start"
       ":margin-top"
       "gtk:grid-attach"
       "gtk:window"
       ":child"
       ":title"
       ":application"
       ":default-width"
       ":default-height"
       "gtk:label"
       ":use-markup"
       ":label"
       "gtk:toggle-button"
       "gtk:widget-visible"
       "g:object-bind-property")
      ("Revealer Swing"
       ":window"
       "DO-REVEALER-SWING"
       "gtk4-example"
       "revealer.lisp"
       :keywords
       "GtkRevealer"
       "gtk:revealer"
       "gtk:align" ":halign" ":valign"
       "gtk:revealer-transition-type" ":transition-type"
       ":transition-duration"
       "gtk:grid"
       ":column-homogeneous"
       ":row-homogeneous"
       ":column-spacing"
       ":row-spacing"
       ":margin-bottom"
       ":margin-end"
       ":margin-start"
       ":margin-top"
       "gtk:grid-attach"
       "gtk:window"
       ":child"
       ":title"
       ":application"
       ":default-width"
       ":default-height"
       "gtk:label"
       ":use-markup"
       ":label"
       "gtk:toggle-button"
       "gtk:widget-visible"
       "g:object-bind-property")
      ("Revealer Icon"
       ":window"
       "DO-REVEALER-ICON"
       "gtk4-example"
       "revealer-icon.lisp"
       "resource/revealer-icon.ui"
       :keywords
       "GtkRevealer"
       "gtk:revealer"
       "gtk:revealer-reveal-child"
       "gtk:revealer-child-revealed"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:window-applicaton"
       "gtk:widget-mapped"
       "g:timeout-add"
       "g:source-remove"
       "g:signal-connect"
       "::close-request"
       "notify::child-revealed")
      ("List Box Complex"
       ":window"
       "DO-LIST-BOX-COMPLEX"
       "gtk4-example"
       "list-box-complex.lisp"
       "resource/list-box-complex.ui"
       "resource/list-box-message.txt"
       :keywords
       "GtkListBox"
       "gtk:list-box"
       ":activate-on-single-click"
       "gtk:list-box-row"
       "gtk:list-box-set-sort-func"
       "gtk:list-box-append"
       "gtk:box"
       "gtk:orientation" ":orientation" ":vertical"
       ":spacing"
       "gtk:box-append"
       "gtk:scrolled-window"
       ":vexpand"
       "gtk:policy-type" ":hscrollbar-policy" ":vscrollbar-policy"
       ":never" ":automatic"
       "gtk:window"
       ":title"
       ":child"
       ":application"
       ":default-width"
       ":default-height"
       "gtk:label"
       ":label"
       ":margin-top"
       "gtk:align" ":valign" ":center"
       "gtk:revealer-reveal-child"
       "gtk:button-label"
       "gtk:image-set-from-file"
       "gtk:label-label"
       "gtk:label-set-markup"
       "gtk:widget-visible"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "g:application-mark-busy"
       "g:application-unmark-busy"
       "gobject:define-gobject-subclass"
       "g:signal-connect"
       "::clicked"
       "::row-activated")
      ("List Box Controls"
       ":window"
       "DO-LIST-BOX-CONTROLS"
       "gtk4-example"
       "list-box-controls.lisp"
       "resource/list-box-controls.ui"
       :keywords
       "GtkListBox"
       "gtk:list-box"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:window-application"
       "gtk:widget-is-ancestor"
       "gtk:switch-active"
       "gtk:check-button-active"
       "gtk:widget-opacity"
       "g:signal-connect"
       "::row-activated")
      ("Flow Box"
       ":window"
       "DO-FLOW-BOX"
       "gtk4-example"
       "flow-box.lisp"
       :keywords
       "GtkFlowBox"
       "GtkFlowBoxChild"
       "gtk:flow-box"
       "gtk:flow-box-child"
       "gtk:flow-box-child-child"
       "gtk:flow-box-invalidate-filter"
       "gtk:flow-box-set-filter-func"
       "gtk:flow-box-set-sort-func"
       "gtk:flow-box-append"
       "gtk:flow-box-select-child"
       ":valign" "gtk:align" ":start"
       ":max-children-per-line"
       ":selection-mode" "gtk:selection-mode" ":single"
       ":homogeneous"
       "gtk:box"
       "gtk:box-append"
       "gtk:orientation" ":orientation" ":vertical"
       "gtk:button"
       ":child"
       ":can-target"
       ":has-frame"
       ":name"
       "gtk:scrolled-window"
       ":vexpand"
       ":hscrollbar-policy" "gtk:policy-type" ":never"
       ":vscrollbar-policy" ":automatic"
       "gtk:window"
       ":title"
       ":application"
       ":default-width"
       ":default-height"
       "gtk:search-entry"
       "gtk:widget-name"
       "gtk:editable-text"
       "gtk:drawing-area-set-draw-func"
       "gdk:rgba-parse"
       "cairo:set-source-rgba"
       "cairo:paint"
       "g:signal-connect"
       "::child-activated")
      ("Stack"
       ":window"
       "DO-STACK"
       "gtk4-example"
       "stack.lisp"
       "resource/stack.ui"
       :keywords
       "GtkStack"
       "gtk:stack"
       "gtk:window-application"
       "gtk:builder-new-from-file"
       "gtk:builder-object")
      ("Stack Sidebar"
       ":window"
       "DO-STACK-SIDEBAR"
       "gtk4-example"
       "stack-sidebar.lisp"
       :keywords
       "GtkStack"
       "GtkStackSidebar"
       "gtk:stack"
       "gtk:stack-sidebar"
       "gtk:stack-add-titled"
       "gtk:header-bar"
       "gtk:image-new-from-icon-name"
       "gtk:image-pixel-size"
       ;; Properties
       ":titlebar"
       ":title-widget"
       ":decoration-layout"
       ":show-title-buttons"
       ":transition-type" "gtk:transition-type" ":slide-up-down"
       ":stack")
      ("Action Bar"
       ":window"
       "DO-ACTION-BAR"
       "gtk4-example"
       "action-bar.lisp"
       :keywords
       "GtkActionBar"
       "gtk:action-bar"
       "gtk:action-bar-pack-start"
       "gtk:action-bar-pack-end"
       "gtk:action-bar-center-widget"
       "gtk:image-new-from-icon-name")
      ("Header Bar"
       ":window"
       "DO-HEADER-BAR"
       "gtk4-example"
       "header-bar.lisp"
       :keywords
       "GtkHeaderBar"
       "gtk:header-bar"
       "gtk:header-bar-pack-start"
       "gtk:widget-add-css-class"
       ;; Properties
       ":decoration-layout"
       ":title-widget"
       ":titlebar"
       ":tooltip-text")
      ("Interactive overlay"
       ":window"
       "DO-OVERLAY-INTERACTIVE"
       "gtk4-example"
       "overlay-interactive.lisp"
       :keywords
       "GtkOverlay"
       "gtk:overlay"
       "gtk:overlay-add-overlay")
      ("Decorative overlay"
       ":window"
       "DO-OVERLAY-DECORATIVE"
       "gtk4-example"
       "overlay-decorative.lisp"
       :keywords
       "GtkOverlay"
       "gtk:overlay"
       "gtk:overlay-add-overlay")
      ("Notebook"
       ":window"
       "DO-NOTEBOOK"
       "gtk4-example"
       "notebook.lisp"
       :keywords
       "GtkNotebook"
       "gtk:notebook"
       "gtk:notebook-add-page"
       "gtk:notebook-tab-detachable"
       "gtk:notebook-tab-reorderable"
       ;; Properties
       ":enable-popup")
      ("Paned Window"
       ":window"
       "DO-PANED"
       "gtk4-example"
       "paned.lisp"
       :keywords
       "GtkPaned"
       "gtk:paned"
       "gtk:paned-start-child"
       "gtk:paned-end-child"
       ;; Properties
       ":position")
      ("Expander"
       ":dialog"
       "CREATE-EXPANDER"
       "gtk4-example"
       "expander.lisp"
       :keywords
       "GtkExpander"
       "gtk:expander"
       "gtk:expander-expanded"
       ;; Signals
       "notify::expanded")
      ("Aspect Frame"
       ":window"
       "DO-ASPECT-FRAME"
       "gtk4-example"
       "aspect-frame.lisp"
       :keywords
       "GtkAspectFrame"
       "gtk:aspect-frame"
       "gtk:drawing-area"
       "gtk:drawing-area-set-draw-func"
       "gtk:widget-color"
       "gdk:cairo-set-source-rgba"
       "cairo:set-source-rgb"
       "cairo:paint"
       "cairo:arc"
       "cairo:fill")
      ("Fixed Container"
       ":window"
       "DO-FIXED"
       "gtk4-example"
       "fixed.lisp"
       :keywords
       "GtkFixed"
       "gtk:fixed"
       "gtk:fixed-put"
       "gtk:fixed-move"
       "gtk:fixed-child-position"
       "gtk:fixed-child-transform"
       "gtk:transform-to-string"
       "gtk:transform-category"
       "gtk:widget-width"
       "gtk:widget-height"))

     ;; Layout Managers
     "Layout Managers"
     (("Fixed Layout"
       ":window"
       "DO-FIXED-LAYOUT"
       "gtk4-example"
       "fixed-layout.lisp"
       :keywords
       "GtkFixed"
       "gtk:fixed"
       "gtk:fixed-put"
       "gtk:fixed-child-transform"
       "gsk:transform"
       "gsk:transform-new"
       "gsk:transform-translate"
       "gsk:transform-translate-3d"
       "gsk:transform-perspective"
       "gsk:transform-rotate-3d"
       "graphene:point-t"
       "graphene:point3d-t"
       "graphene:point3d-init"
       "graphene:vec3-x-axis"
       "graphene:vec3-y-axis")
      ("Simple Constraints"
       ":window"
       "DO-CONSTRAINT-SIMPLE"
       "gtk4-example"
       "constraint-simple.lisp"
       :keywords
       "GtkConstraintLayout"
       "gtk:constraint-layout"
       "gtk:constraint-layout-new"
       "gtk:constraint-layout-add-guide"
       "gtk:constraint-layout-add-constraint"
       "gtk:constraint-new-constant"
       "gtk:widget-class-layout-manager-type"
       "gtk:widget-layout-manager"
       "gtk:widget-set-parent"
       "gtk:box-append"
       "gobject:define-gobject-subclass")
      ("Interactive Constraints"
       ":window"
       "DO-CONSTRAINT-INTERACTIVE"
       "gtk4-example"
       "constraint-interactive.lisp"
       :keywords
       "GtkConstraintLayout"
       "gtk:constraint-layout"
       "gtk:constraint-layout-new"
       "gtk:constraint-layout-add-guide"
       "gtk:constraint-layout-add-constraint"
       "gtk:constraint-layout-remove-constraint"
       "gtk:constraint-new-constant"
       "gtk:constraint-new"
       "gtk:constraint-guide-new"
       "gtk:gesture-drag-new"
       "gtk:gesture-drag-start-point"
       "gtk:widget-add-controller"
       "gtk:widget-set-parent"
       "gtk:widget-class-layout-manager-type"
       "gtk:widget-layout-manager"
       "gtk:widget-queue-allocate"
       "gtk:box-append"
       "gobject:define-gobject-subclass"
       "g:signal-connect"
       "::drag-update")
      ("Constraints Builder"
       ":window"
       "DO-CONSTRAINT-BUILDER"
       "gtk4-example"
       "constraint-builder.lisp"
       "resource/constraint-builder.ui"
       :keywords
       "GtkConstraintLayout"
       "gtk:constraint-layout"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:window-application"
       "gobject:define-gobject-subclass"))

     "Display Widgets"
     (("Various Label"
       ":window"
       "DO-LABEL-VARIOUS"
       "gtk4-example"
       "label-various.lisp"
       :keywords
       "GtkLabel"
       "gtk:label"
       "gtk:separator-new"
       ;; Properties
       ":xalign"
       ":use-markup"
       ":label"
       ":justify" "gtk:justification" ":center" ":right" ":fill"
       ":use-underline"
       ":selectable"
       ":wrap")
      ("Images and Pictures"
       ":window"
       "DO-IMAGES"
       "gtk4-example"
       "images.lisp"
       :keywords
       "GtkImage" "gtk:image"
       "GtkPicture" "gtk:picture"
       "GdkPaintable" "gdk:paintable"
       "GdkTexture" "gdk:texture"
       "GdkPixbufLoader" "gdk:pixbuf-loader"
       "GdkPixbufAnimation" "gdk:pixbuf-animation"
       "GdkPixbufAnimationIter" "gdk:pixbuf-animation-iter")
      ("Spinner"
       ":window"
       "DO-SPINNER"
       "gtk4-example"
       "spinner.lisp"
       :keywords
       "GtkSpinner"
       "gtk:spinner"
       "gtk:spinner-new"
       "gtk:spinner-start"
       "gtk:spinner-stop")
      ("Info Bar"
       ":window"
       "DO-INFO-BAR"
       "gtk4-example"
       "info-bar.lisp"
       :keywords
       "GtkInfoBar"
       "gtk:info-bar"
       "gtk:info-bar-add-child"
       "gtk:info-bar-add-button"
       "gtk:info-bar-message-type"
       "gtk:widget-hide"
       ;; Properties
       ":no-show-all")
      ("Progress Bar"
       ":window"
       "DO-PROGRESS-BAR"
       "gtk4-example"
       "progress-bar.lisp"
       :keywords
       "GtkProgressBar"
       "gtk:progress-bar"
       "gtk:progress-bar-pulse"
       "gtk:progress-bar-fraction"
       "gtk:progress-bar-text"
       "gtk:progress-bar-show-text"
       "gtk:progress-bar-inverted"
       "gtk:css-provider-new"
       "gtk:css-provider-load-from-string"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       "g:timeout-add"
       "g:source-remove"
       "g:+source-continue+")
      ("Level Bar"
       ":window"
       "DO-LEVEL-BAR"
       "gtk4-example"
       "level-bar.lisp"
       :keywords
       "GtkLevelBar"
       "gtk:level-bar"
       "gtk:level-bar-max-value"
       "gtk:level-bar-add-offset-value"
       "gtk:css-provider-new"
       "gtk:css-provider-load-from-string"
       "gtk:widget-add-css-class"
       "gtk:widget-add-provider"
       "g:object-bind-property")
      ("Statusbar"
       ":window"
       "DO-STATUSBAR"
       "gtk4-example"
       "statusbar.lisp"
       :keywords
       "GtkStatusbar"
       "gtk:statusbar"
       "gtk:statusbar-context-id"
       "gtk:statusbar-push"
       "gtk:statusbar-pop")
      ("Calendar"
       ":window"
       "DO-CALENDAR"
       "gtk4-example"
       "calendar.lisp"
       :keywords
       "GtkCalendar"
       "gtk:calendar"
       "gtk:calendar-day"
       "gtk:calendar-month"
       "gtk:calendar-year"
       "gtk:calendar-mark-day"))

     "List-based widgets"
     (("Application Launcher"
       ":window"
       "DO-LIST-VIEW-APPLAUNCHER"
       "gtk4-example"
       "list-view-applauncher.lisp"
       :keywords
       "GtkListView"
       "gtk:list-view"
       "gtk:list-view-new"
       "gtk:list-view-model"
       "gtk:list-model-object"
       "gtk:list-item-child"
       "gtk:list-item-item"
       "gtk:single-selection-new"
       "gtk:signal-list-item-factory-new"
       "gtk:alert-dialog-show"
       "gtk:widget-display"
       "gtk:widget-root"
       "gtk:widget-first-child"
       "gtk:widget-next-sibling"
       "gtk:image-set-from-gicon"
       "gdk:display-app-launch-context"
       "g:list-store-new"
       "g:list-store-append"
       "g:app-info-all"
       "g:app-info-launch"
       "g:app-info-display-name"
       "g:app-info-icon")

      ("World Clocks"
       ":window"
       "DO-GRID-VIEW-CLOCKS"
       "gtk4-example"
       "grid-view-clocks.lisp"
       :keywords
       ;; TODO: Add more keywords
       "GtkGridView"
       "gtk:grid-view"
       "define-gobject-subclass"
       "gdk:paintable"
       "gdk:paintable-snapshot")

; TODO: The example is not finished
;      ("Colors"
;       ":window"
;       "DO-GRID-VIEW-COLORS"
;       "gtk4-example"
;       "grid-view-colors.lisp")

; TODO: This example is not finished
      ("Drop Down"
       ":window"
       "DO-DROP-DOWN"
       "gtk4-example"
       "drop-down.lisp"
       :keywords
       "GtkDropDown"
       "gtk:drop-down"))

     "Media Support"
     (("Video"
       ":window"
       "DO-VIDEO"
       "gtk4-example"
       "video.lisp"
       :keywords
       "GtkVideo" "gtk:video"))

     "Button and Toggle Widgets"
     (("Various Buttons"
       ":window"
       "DO-BUTTON-VARIOUS"
       "gtk4-example"
       "button-various.lisp"
       :keywords
       "GtkButton"
       "gtk:button"
       "gtk:button-new-with-label"
       "gtk:button-new-with-mnemonic"
       "gtk:button-new-with-icon-name"
       "GtkSizeGroup"
       "gtk:size-group")
      ("Toggle Buttons"
       ":window"
       "DO-TOGGLE-BUTTON"
       "gtk4-example"
       "toggle-button.lisp")
      ("Toggle Buttons Action"
       ":window"
       "DO-TOGGLE-BUTTON-ACTION"
       "gtk4-example"
       "toggle-button-action.lisp")
      ("Check Buttons"
       ":window"
       "DO-CHECK-BUTTON"
       "gtk4-example"
       "check-button.lisp"
       :keywords
       "GtkCheckbutton"
       "gtk:check-button"
       "gtk:check-button-new-with-label"
       "gtk:check-button-new-with-mnemonic"
       "gtk:check-button-group"
       "gtk:check-button-active")
      ("Menu Buttons"
       ":window"
       "DO-MENU-BUTTON"
       "gtk4-example"
       "menu-button.lisp")
      ("Link Button"
       ":window"
       "DO-LINK-BUTTON"
       "gtk4-example"
       "link-button.lisp"
       :keywords
       "GtkLinkButton"
       "gtk:link-button"
       "gtk:link-button-new"
       "gtk:link-button-new-with-label"
       "gtk:link-button-visited"
       ":visited")
      ("Scale Button"
       ":window"
       "DO-SCALE-BUTTON"
       "gtk4-example"
       "scale-button.lisp")
      ("Switch"
       ":window"
       "DO-SWITCH"
       "gtk4-example"
       "switch.lisp"
       :keywords
       "GtkSwitch"
       "gtk:switch"
       "gtk:switch-active"
       ":active"
       "notify::active"))

     "Numeric/Text Data Entry"
     (("Entry"
       ":window"
       "DO-ENTRY"
       "gtk4-example"
       "entry.lisp"
       :keywords
       "GtkEntry"
       "gtk:entry"
       "gtk:entry-text-length"
       "gtk:entry-visibility"
       "gtk:entry-buffer"
       "gtk:editable-insert-text"
       "gtk:editable-editable"
       "gtk:check-button-new-with-label"
       "gtk:check-button-active"
       "gtk:box"
       "gtk:box-append"
       "gtk:window"
       "g:signal-connect"
       "g:signal-handler-block"
       "g:signal-stop-emission"
       "g:signal-handler-unblock"
       "::insert-text"
       "::toggled"
       ":orientation"
       ":spacing"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       ":application"
       ":child"
       ":title"
       ":default-width"
       ":default-height"
       ":resizable"
       ":text"
       ":buffer"
       ":max-length")
      ("Entry Buffer"
       ":window"
       "DO-ENTRY-BUFFER"
       "gtk4-example"
       "entry-buffer.lisp"
       :keywords
       "GtkEntry"
       "GtkEntryBuffer"
       "gtk:entry"
       "gtk:entry-buffer"
       "gtk:box"
       "gtk:label"
       "gtk:window"
       ":orientation"
       ":spacing"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       ":title"
       ":child"
       ":application"
       ":default-width"
       ":resizable"
       ":label"
       ":halign"
       ":use-markup"
       ":valign"
       ":wrap"
       ":buffer")
      ("Entry Completion"
       ":window"
       "DO-ENTRY-COMPLETION"
       "gtk4-example"
       "entry-completion.lisp"
       :keywords
       "GtkEntryCompletion"
       "gtk:entry-completion"
       "gtk:entry"
       "gtk:list-store"
       "gtk:list-store-set"
       "gtk:list-store-append"
       "gtk:box"
       "gtk:box-append"
       ":orientation" ":horizontal"
       ":spacing"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       "gtk:label"
       "gtk:window"
       ":title"
       ":child"
       ":application"
       ":default-width"
       ":resizable"
       ":label"
       ":halign"
       ":valign"
       ":use-markup"
       ":wrap"
       ":text-column"
       ":inline-completion"
       ":popup-completion"
       ":model"
       ":completion")
      ("Password Entry"
       ":window"
       "DO-PASSWORD-ENTRY"
       "gtk4-example"
       "password-entry.lisp"
       :keywords
       "GtkPasswordEntry"
       "gtk:password-entry"
       "gtk:editable-text"
       "gtk:header-bar"
       "gtk:header-bar-pack-end"
       "gtk:header-bar-pack-start"
       "gtk:widget-sensitive"
       "gtk:widget-add-css-class"
       "gtk:widget-root"
       ;; Style classes
       ".suggest-action"
       ;; Properties
       ":show-peek-icon"
       ":placeholder-text"
       ":activates-default"
       ":show-title-buttons"
       ;; Signals
       "notify::text"
       "::clicked")
      ("Scale Widgets"
       ":window"
       "DO-SCALE-WIDGET"
       "gtk4-example"
       "scale-widget.lisp"
       :keywords
       "GtkScale"
       "gtk:scale"
       "gtk:scale-draw-value"
       "gtk:scale-add-mark"
       "gtk:scale-clear-marks"
       "gtk:scale-value-pos"
       "gtk:adjustment"
       "gtk:adjustment-lower"
       "gtk:adjustment-upper"
       "gtk:adjustment-value"
       "gtk:range-adjustment"
       "gtk:check-button-active"
       ;; Properties
       ":digits"
       ":value-pos"
       ":draw-value"
       ":adjustment"
       ":value"
       ":lower"
       ":upper"
       ":step-increment")
      ("Spin Button"
       ":window"
       "DO-SPIN-BUTTON"
       "gtk4-example"
       "spin-button.lisp")
      ("Search Bar"
       ":window"
       "DO-SEARCH-BAR"
       "gtk4-example"
       "search-bar.lisp"
       :keywords
       "gtk:search-bar"
       "gtk:search-entry"
       "gtk:search-bar-key-capture-widget"
       "gtk:search-bar-connect-entry"))

     "Multiline Text Editor"
     (("Simple Text View"
       ":window"
       "DO-TEXT-VIEW-SIMPLE"
       "gtk4-example"
       "text-view-simple.lisp")
      ("Text View Attributes"
       ":window"
       "DO-TEXT-VIEW-ATTRIBUTES"
       "gtk4-example"
       "text-view-attributes.lisp")
      ("Text View Tags"
       ":window"
       "DO-TEXT-VIEW-TAGS"
       "gtk4-example"
       "text-view-tags.lisp")
      ("Text View Search"
       ":window"
       "DO-TEXT-VIEW-SEARCH"
       "gtk4-example"
       "text-view-search.lisp")
      ("Hypertext"
       ":window"
       "DO-TEXT-VIEW-HYPERTEXT"
       "gtk4-example"
       "text-view-hypertext.lisp")
      ("Markup"
       ":window"
       "DO-TEXT-VIEW-MARKUP"
       "gtk4-example"
       "text-view-markup.lisp")
      ("Tabulator"
       ":window"
       "DO-TEXT-VIEW-TABS"
       "gtk4-example"
       "text-view-tabs.lisp")
      ("Multiple"
       ":window"
       "DO-TEXT-VIEW-MULTIPLE"
       "gtk4-example"
       "text-view-multiple.lisp")
      ("Undo and Redo"
       ":window"
       "DO-TEXT-VIEW-undo"
       "gtk4-example"
       "text-view-undo.lisp")
      ("Scrolling"
       ":window"
       "DO-TEXT-VIEW-SCROLL"
       "gtk4-example"
       "text-view-scroll.lisp"))

     "Tree, List and Icon Grid Widgets"
     (("Simple Tree View"
       ":window"
       "DO-TREE-VIEW-SIMPLE"
       "gtk4-example"
       "tree-view-simple.lisp")
      ("Tree View Path"
       ":window"
       "DO-TREE-VIEW-PATH"
       "gtk4-example"
       "tree-view-path.lisp")
      ("Tree View Content Type"
       ":window"
       "DO-TREE-VIEW-CONTENT-TYPE"
       "gtk4-example"
       "tree-view-content-type.lisp"))

     "Menus, Combo Box, Toolbar"
     (("Combo Box"
       ":window"
       "DO-COMBO-BOX"
       "gtk4-example"
       "combo-box.lisp"
       :keywords
       "GtkComboBox"
       "gtk:combo-box"
       "gtk:combo-box-set-row-separator-func"
       "gtk:combo-box-active-id"
       "gtk:combo-box-id-column"
       "gtk:combo-box-active"
       "gtk:combo-box-set-row-separator-func"
       "gtk:combo-box-active-id"
       "gtk:tree-model-path"
       "gtk:tree-model-value"
       "gtk:tree-path-to-string"
       "gtk:cell-renderer-pixbuf-new"
       "gtk:cell-renderer-xpad"
       "gtk:cell-layout-pack-start"
       "gtk:cell-layout-set-attributes"
       "gtk:cell-layout-set-cell-data-func"
       "gtk:cell-renderer-text"
       "gtk:cell-renderer-sensitive"
       "gtk:label-set-markup"
       "gtk:box-append"
       "gtk:list-store-new"
       "gtk:list-store-append"
       "gtk:list-store-set"
       "g:signal-connect"
       "::changed")
      ("Combo Box Text"
       ":window"
       "DO-COMBO-BOX-TEXT"
       "gtk4-example"
       "combo-box-text.lisp"
       :keywords
       "GtkComboBoxText"
       "gtk:combo-box"
       "gtk:combo-box-active"
       "gtk:combo-box-child"
       "gtk:combo-box-text"
       "gtk:combo-box-text-append-text"
       "gtk:combo-box-text-active-text"
       "gtk:combo-box-text-remove"
       "gtk:box-append"
       "g:signal-connect"
       "::changed"
       "::icon-press"))

     "Selectors (Color/File/Font)"
     (("Color Button"
       ":window"
       "DO-COLOR-BUTTON"
       "gtk4-example"
       "color-button.lisp"
       :keywords
       "GtkColorButton"
       "gtk:color-button"
       "gtk:color-chooser-rgba"
       "gtk:window"
       "gdk:rgba-parse"
       "gdk:rgba-to-string"
       "g:signal-connect"
       "::color-set"
       ":rgba"
       ":title"
       ":margin-top"
       ":margin-buttom"
       ":margin-start"
       ":margin-end"
       ":application"
       ":child"
       ":default-width"
       ":default-height")
      ("Color Button Label"
       ":window"
       "DO-COLOR-BUTTON-LABEL"
       "gtk4-example"
       "color-button-label.lisp"
       :keywords
       "GtkColorButton"
       "gtk:color-button"
       "gtk:color-chooser-rgba"
       "gtk:window"
       "gtk:box"
       "gtk:box-append"
       "gtk:label"
       "gdk:rgba-parse"
       "gdk:rgba-to-string"
       "gtk:css-provider-new"
       "gtk:css-provider-load-from-string"
       "gtk:widget-add-provider"
       "g:signal-emit"
       "g:signal-connect"
       "::color-set"
       ":orientation"
       ":spacing"
       ":margin-top"
       ":margin-bottom"
       ":margin-start"
       ":margin-end"
       ":application"
       ":child"
       ":title"
       ":default-width"
       ":default-height"
       ":css-name"
       ":label"
       ":use-markup"
       ":rgba"
       ":width-request"
       ":height-request")
      ("Color Chooser Dialog"
       ":window"
       "DO-COLOR-CHOOSER-DIALOG"
       "gtk4-example"
       "color-chooser-dialog.lisp"
       :keywords
       "GtkColorChooserDialog"
       "gtk:color-chooser-dialog"
       "gtk:color-chooser-add-palette"
       "gtk:color-chooser-rgba"
       "gtk:drawing-area"
       "gtk:drawing-area-set-draw-func"
       "gtk:widget-add-controller"
       "gtk:widget-queue-draw"
       "gtk:gesture-click"
       "gtk:window"
       "gtk:window-destroy"
       "gdk:rgba-red"
       "gdk:rgba-green"
       "gdk:rgba-blue"
       "gdk:rgba-parse"
       "g:signal-connect"
       "cairo:set-source-rgb"
       "cairo:paint"
       "cairo:select-font-face"
       "cairo:set-font-size"
       "cairo:move-to"
       "cairo:show-text"
       "::pressed"
       "::response"
       ":application"
       ":title"
       ":child"
       ":default-width"
       ":transient-for"
       ":use-alpha")
      ("Color Chooser Widget"
       ":window"
       "DO-COLOR-CHOOSER-WIDGET"
       "gtk4-example"
       "color-chooser-widget.lisp"
       :keywords
       "GtkColorChooserWidget"
       "gtk:color-chooser-widget"
       "gdk:rgba-to-string"
       "g:signal-connect"
       "::color-activated")
      ("Color Chooser Palette"
       ":window"
       "DO-COLOR-CHOOSER-PALETTE"
       "gtk4-example"
       "color-chooser-palette.lisp"
       :keywords
       "GtkColorChooserWidget"
       "gtk:color-chooser-widget"
       "gtk:color-chooser-add-palette"
       "gtk:builder-new-from-string"
       "gtk:builder-object"
       "gtk:combo-box-active"
       "gtk:combo-box-text-active-text"
       "gtk:box-append"
       "gdk:rgba-parse"
       "g:signal-connect"
       "::changed")
      ("File Chooser Dialog"
       ":dialog"
       "CREATE-FILE-CHOOSER-DIALOG"
       "gtk4-example"
       "file-chooser-dialog.lisp"
       :keywords
       "GtkFileChooserDialog"
       "gtk:file-chooser-dialog")
      ("File Chooser Native"
       ":dialog"
       "CREATE-FILE-CHOOSER-NATIVE"
       "gtk4-example"
       "file-chooser-native.lisp"
       :keywords
       "GtkFileChooserNative"
       "gtk:file-chooser-native")
      ("Font Button"
       ":window"
       "DO-FONT-BUTTON"
       "gtk4-example"
       "font-button.lisp")
      ("Font Button Label"
       ":window"
       "DO-FONT-BUTTON-LABEL"
       "gtk4-example"
       "font-button-label.lisp"))

     "Widgets for custom drawing"
     (("Drawing Area"
       ":window"
       "DO-DRAWING-AREA"
       "gtk4-example"
       "drawing-area.lisp"
       :keywords
       "GtkDrawingArea"
       "gtk:drawing-area"
       "gtk:drawing-area-set-draw-func"
       "gtk:widget-color"
       "gtk:window"
       "gdk:cairo-set-source-rgba"
       "cairo:arc"
       "cairo:fill"
       ":application"
       ":child"
       ":title"
       ":default-width"
       ":default-height")
      ("Scribble on Drawing Area"
       ":window"
       "DO-DRAWING-AREA-SCRIBBLE"
       "gtk4-example"
       "drawing-area-scribble.lisp"
       :keywords
       "GtkDrawingArea"
       "gtk:drawing-area"
       "gtk:drawing-area-set-draw-func"
       "gtk:widget-width"
       "gtk:widget-height"
       "gtk:widget-queue-draw"
       "gtk:widget-add-controller"
       "gtk:window"
       "gtk:frame"
       "gtk:gesture-drag"
       "gdk:rectangle-new"
       "cairo:destroy"
       "cairo:surface-destroy"
       "cairo:image-surface-create"
       "cairo:with-context"
       "cairo:set-source-rgb"
       "cairo:set-source-surface"
       "cairo:paint"
       "cairo:image-surface-width"
       "cairo:image-surface-height"
       "cairo:rectangle"
       "cairo:fill"
       "g:signal-connect"
       "::destroy"
       "::resize"
       "::drag-begin"
       "::drap-update"
       "::drag-end"
       ":content-height"
       ":content-width"
       ":child"
       ":application"
       ":title"
       ":default-width"
       ":button"))

     "Ornaments"
     (("Frame"
       ":window"
       "DO-FRAME"
       "gtk4-example"
       "frame.lisp")
      ("Frame Properties"
       ":window"
       "DO-FRAME-PROPERTIES"
       "gtk4-example"
       "frame-properties.lisp"))

     "Scrolling"
     (("Scrolled Window"
       ":window"
       "DO-SCROLLED-WINDOW"
       "gtk4-example"
       "scrolled-window.lisp"))

     "Printing"
     (#-windows
      ("Page Setup Dialog"
       ":dialog"
       "CREATE-PAGE-SETUP-DIALOG"
       "gtk4-example"
       "page-setup-dialog.lisp"
       "resource/page-setup.ini"))

     "Drag and Drop, Clipboard"
     (("Clipboard"
       ":window"
       "DO-CLIPBOARD"
       "gtk4-example"
       "clipboard.lisp"
       "resource/clipboard.ui"
       :keywords
       "GdkClipboard"
       "gdk:clipboard"
       "gdk:clipboard-formats"
       "gdk:clipboard-set"
       "gdk:clipboard-set-text"
       "gdk:clipboard-read-value-async"
       "gdk:clipboard-read-value-finish"
       "gdk:content-provider-new-for-value"
       "gdk:content-formats-contain-gtype"
       "gtk:widget-clipboard"
       "notify::visible-child"
       "notify::text"
       "::changed"
       "::clicked"
       "::drop"
       "::prepare")
     )

     "Paintable"
     (("Nuclear Icon"
       ":window"
       "DO-PAINTABLE-SIMPLE"
       "gtk4-example"
       "paintable-simple.lisp")
      ("Nuclear Animation"
       ":window"
       "DO-PAINTABLE-ANIMATION"
       "gtk4-example"
       "paintable-animation.lisp")
      ("Emblemed Icons"
       ":window"
       "DO-PAINTABLE-EMBLEM"
       "gtk4-example"
       "paintable-emblem.lisp"))

     "Subclassing"
     (("GtkFigure subclass"
       ":window"
       "DO-SUBCLASSING-FIGURE"
       "gtk4-example"
       "subclassing-figure.lisp"))

     ;; Pango demos
     "Pango"
     (("Draw centered text"
       ":drawfunc"
       "pango-draw-text-centered"
       "pango-example"
       "text-centered.lisp")

      ("Draw text metrics"
       ":drawfunc"
       "pango-draw-text-metrics"
       "pango-example"
       "text-metrics.lisp")

      ("Draw text soulmate"
       ":drawfunc"
       "pango-draw-text-soulmate"
       "pango-example"
       "text-soulmate.lisp")
      ("Pango Cairo rendering"
       ":drawfunc"
       "pango-draw-cairo-rendering"
       "pango-example"
       "cairo-rendering.lisp")
      ("Draw Pango Layout"
       ":drawfunc"
       "draw-pango-layout"
       "pango-example"
       "draw-pango-layout.lisp")
       )

     ;; Cairo demos
     "Cairo"
     ("Examples from cairographics.org"
      (("Arc"
        ":drawfunc"
        "draw-arc"
        "cairo-example"
        "draw-arc.lisp")
       ("Arc Negative"
        ":drawfunc"
        "draw-arc-negative"
        "cairo-example"
        "draw-arc-negative.lisp")
       ("Clip"
        ":drawfunc"
        "draw-clip"
        "cairo-example"
        "draw-clip.lisp")
       ("Clip Image"
        ":drawfunc"
        "draw-clip-image"
        "cairo-example"
        "draw-clip-image.lisp")
       ("Curve To"
        ":drawfunc"
        "draw-curve-to"
        "cairo-example"
        "draw-curve-to.lisp")
       ("Dash"
        ":drawfunc"
        "draw-dash"
        "cairo-example"
        "draw-dash.lisp")
       ("Preserve Fill"
        ":drawfunc"
        "draw-fill-preserve"
        "cairo-example"
        "draw-fill-preserve.lisp")
       ("Fill Style"
        ":drawfunc"
        "draw-fill-style"
        "cairo-example"
        "draw-fill-style.lisp")
       ("Gradient"
        ":drawfunc"
        "draw-gradient"
        "cairo-example"
        "draw-gradient.lisp")
       ("Image"
        ":drawfunc"
        "draw-image"
        "cairo-example"
        "draw-image.lisp")
       ("Image Pattern"
        ":drawfunc"
        "draw-image-pattern"
        "cairo-example"
        "draw-image-pattern.lisp")
       ("Multi Caps"
        ":drawfunc"
        "draw-multi-caps"
        "cairo-example"
        "draw-multi-caps.lisp")
       ("Rounded Rectangle"
        ":drawfunc"
        "draw-rounded-rectangle"
        "cairo-example"
        "draw-rounded-rectangle.lisp")
       ("Line Cap"
        ":drawfunc"
        "draw-line-cap"
        "cairo-example"
        "draw-line-cap.lisp")
       ("Line Join"
        ":drawfunc"
        "draw-line-join"
        "cairo-example"
        "draw-line-join.lisp")
       ("Text"
        ":drawfunc"
        "draw-text"
        "cairo-example"
        "draw-text.lisp")
       ("Text Align Center"
        ":drawfunc"
        "draw-text-align-center"
        "cairo-example"
        "draw-text-align-center.lisp")
       ("Text Extents"
        ":drawfunc"
        "draw-text-extents"
        "cairo-example"
        "draw-text-extents.lisp"))

      "More Examples"
      (("Cairo Stroke"
       ":drawfunc"
       "cairo-draw-stroke"
       "cairo-example"
       "draw-stroke.lisp")
       ("Cairo Fill"
        ":drawfunc"
        "cairo-draw-fill"
        "cairo-example"
        "draw-fill.lisp")
       ("Cairo Text Letter"
        ":drawfunc"
        "cairo-draw-text-letter"
        "cairo-example"
        "draw-text-letter.lisp")
       ("Cairo Paint"
        ":drawfunc"
        "cairo-draw-paint"
        "cairo-example"
        "draw-paint.lisp")
       ("Cairo Mask"
        ":drawfunc"
        "cairo-draw-mask"
        "cairo-example"
        "draw-mask.lisp")
       ("Cairo Source RGBA"
        ":drawfunc"
        "cairo-draw-source-rgba"
        "cairo-example"
        "draw-source-rgba.lisp")
       ("Cairo Source Gradient"
        ":drawfunc"
        "cairo-draw-source-gradient"
        "cairo-example"
        "draw-source-gradient.lisp")
       ("Cairo Path"
        ":drawfunc"
        "cairo-draw-path"
        "cairo-example"
        "draw-path.lisp")
       ("Cairo Dashes"
        ":drawfunc"
        "cairo-draw-dashes"
        "cairo-example"
        "draw-dashes.lisp")
       ("Cairo Joins"
        ":drawfunc"
        "cairo-draw-joins"
        "cairo-example"
        "draw-joins.lisp")
       ("Cairo Text centered"
        ":drawfunc"
        "cairo-draw-text-centered"
        "cairo-example"
        "draw-text-centered.lisp")
       ("Cairo Text Glyph"
        ":drawfunc"
        "cairo-draw-text-glyph"
        "cairo-example"
        "draw-text-glyph.lisp")
       ("Cairo Text Gradient"
        ":drawfunc"
        "cairo-draw-text-gradient"
        "cairo-example"
        "draw-text-gradient.lisp")
       ("Cairo Text Shaded"
        ":drawfunc"
        "cairo-draw-text-shaded"
        "cairo-example"
        "draw-text-shaded.lisp")
       ("Cairo Text Soulmate"
        ":drawfunc"
        "cairo-draw-text-soulmate"
        "cairo-example"
        "draw-text-soulmate.lisp")
       ("Cairo Draw Logo"
        ":drawfunc"
        "cairo-draw-logo"
        "cairo-example"
        "draw-logo.lisp")
       ("Cairo Draw Logo Translate"
        ":drawfunc"
        "cairo-draw-logo-translate"
        "cairo-example"
        "draw-logo.lisp")))
     "Miscellaneous"
     (("Cursors"
       ":window"
       "DO-CURSORS"
       "gtk4-example"
       "cursors.lisp"
       "resource/cursors.ui"
       :keywords
       "GdkCursor"
       "gdk:cursor"
       "gtk:builder-new-from-file"
       "gtk:builder-object"
       "gtk:window-application")
      ("Size Groups"
       ":window"
       "DO-SIZE-GROUP"
       "gtk4-example"
       "size-group.lisp")
      ("GdkAppLaunchContext"
       ":window"
       "DO-APP-LAUNCH-CONTEXT"
       "gtk4-example"
       "app-launch-context.lisp"
       :keywords
       "GdkAppLaunchContext"
       "gdk:app-launch-context"
       "gdk:app-launch-context-default-for-uri"
       "gdk:app-launch-context-set-timestamp"
       "gdk:display-app-launch-context"
       "gtk:widget-display"
       "g:app-info-launch-default-for-uri"
       "g:app-info-name"
       "g:type-from-instance"
       "g:variant-print"
       "g:variant-type-string"
       "gdk:+current-time+"
       "::launched")
      ("GdkAppLaunchContext Asyn"
       ":window"
       "DO-APP-LAUNCH-CONTEXT-ASYNC"
       "gtk4-example"
       "app-launch-context.lisp"
       :keywords
       "GdkAppLaunchContext"
       "gdk:app-launch-context"
       "gdk:display-app-launch-context"
       "gtk:widget-display"
       "g:app-info-launch-default-for-uri-async"
       "g:app-info-launch-default-for-uri-finish"))
))
